/*
 * Generated by Bluespec Compiler, version 2019.05.beta2 (build a88bf40, 2019-05-24)
 * 
 * On Sat Jun 24 13:51:19 CST 2023
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkTests_h__
#define __mkTests_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTests module */
class MOD_mkTests : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Fifo<tUInt32> INST_answerFifo;
  MOD_Fifo<tUInt64> INST_rsp_entry;
  MOD_Fifo<tUInt64> INST_rsp_stage1_1bit;
  MOD_Fifo<tUInt64> INST_rsp_stage2_2bits;
  MOD_Fifo<tUInt64> INST_rsp_stage3_4bits;
  MOD_Fifo<tUInt64> INST_rsp_stage4_8bits;
  MOD_Fifo<tUInt64> INST_rsp_stage5_16bits;
  MOD_Reg<tUInt32> INST_tbCounter;
 
 /* Constructor */
 public:
  MOD_mkTests(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_test;
  tUInt8 DEF_CAN_FIRE_RL_test;
  tUInt8 DEF_WILL_FIRE_RL_run;
  tUInt8 DEF_CAN_FIRE_RL_run;
  tUInt8 DEF_WILL_FIRE_RL_rsp_rule5;
  tUInt8 DEF_CAN_FIRE_RL_rsp_rule5;
  tUInt8 DEF_WILL_FIRE_RL_rsp_rule4;
  tUInt8 DEF_CAN_FIRE_RL_rsp_rule4;
  tUInt8 DEF_WILL_FIRE_RL_rsp_rule3;
  tUInt8 DEF_CAN_FIRE_RL_rsp_rule3;
  tUInt8 DEF_WILL_FIRE_RL_rsp_rule2;
  tUInt8 DEF_CAN_FIRE_RL_rsp_rule2;
  tUInt8 DEF_WILL_FIRE_RL_rsp_rule1;
  tUInt8 DEF_CAN_FIRE_RL_rsp_rule1;
 
 /* Local definitions */
 private:
  tUInt32 DEF_operand__h17927;
 
 /* Rules */
 public:
  void RL_rsp_rule1();
  void RL_rsp_rule2();
  void RL_rsp_rule3();
  void RL_rsp_rule4();
  void RL_rsp_rule5();
  void RL_run();
  void RL_test();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTests &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTests &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTests &backing);
};

#endif /* ifndef __mkTests_h__ */
